version: '3.3'
services:
  redis:
    image: redis
    restart: always
    container_name: 'geo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    command: sh web-entrypoint.sh
    environment:
      #      DJANGO_SETTINGS_MODULE: "project.settings.development"
      DEBUG: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db

    volumes:
      - .:/sibwater_site
    ports:
      - "${HTTP_PORT:-8000}:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    ports:
      - "${DB_PORT:-5432}:5432"
  celery:
    build: .
    container_name: 'geo_app_celery'
    command: celery -A core worker -B
    volumes:
      - .:/sibwater_site
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  postgres_data:


#https://webdevblog.ru/kak-ispolzovat-django-postgresql-i-docker/:
#
#
#    https://dev-gang.ru/article/naczalo-raboty-s-docker-i-django-73cvl13n55/: